#!/bin/bash
# count the lines per days
if [ -z $1 ] || [ -z $2 ] || [ -z $3 ];
then
    echo "----------------------"
    echo "ERR: missing arguments."
    echo "usage: cat count_per_days_file | ./get-keywords global_word_count_file 0.8 1 | tee output"
    exit 0
fi

awk -v file=$1 -F'[ ]' '
BEGIN { 
 while ((getline < file ) > 0) {
  #print $2 " " $3
  GWC[$2] = $3
 }
 #print "ENDED LOADING GWC"
}
{ 
 #print $1 "!!-- " $2 "==" $4 "." $3 "-" GWC[$3]
 if (GWC[$3] > 0) words[$1 " " $3] = ( $4 / GWC[$3] )
} 
END { 
  for (w in words) { printf " %s %5.2f\n", w, words[w] } 
}' | sort -nr --key=3 | awk -v minscore=$2 -v showscore=$3 '
{
 dates[$1] = (dates[$1] ($3 > minscore ? ( $2 " " (showscore ? $3 " " : "" ) ) : "")) 
} 
END { 
 for (d in dates) { printf "%s : %s\n", d, dates[d] } 
}' | sort