#!/bin/bash
#we split the lines into date|time|user|text , we also zero pad the month and day (for sorting)
sed 's/^\[\([0-9]\+\)\/\([0-9]\+\)/000\1\/000\2/;s/^0\+\([0-9]\{2\}\)\/0\+\([0-9]\{2\}\)\/\([0-9]\+\) \([0-9]\+\):\([0-9]\+\):\([0-9]\+\) \([A-Z]\+\) *\] *\([A-Za-z ]\+\):/|\3-\1-\2|\4-\5-\7|\8|/' | grep "^|" 