#!/bin/bash
# count the lines per days
awk 'BEGIN { RS=" " } { if (length($1) > 2) print tolower($1) } END { print "" }' |  sed 's/^[\~(!"_-]*\([a-z]\+\).*/\1/' | awk  '{if (length($1) > 2) print $1 } END { print "" }'